### PR TITLE
Compiler adjustments

### PR DESCRIPTION
**Pull request by sgrottel**
I am using you classes in a little experiment project, which will eventually become a contribution for another open source project. That is why I am using that's project compiler settings, including different compilers and "treat warnings as errors". I did some minor modifications to your classes to resolve some warnings/errors.

I can either maintain my changes in my own fork, or I can send you pull requests. Your call.

### CODE REVIEW

**Comment by possibly-wrong** [comment]
Thanks for letting me know about these issues, I would like to help get these fixed. Would you be able to point me to an example test case, and any of the specific compilers and warning settings that you're using? I would like to reproduce and better understand the warnings-- the only ones that I can actually reproduce are the ones in `math::Unsigned` (the shadowing of the loop index variable `i` with `--Wshadow` in GCC, and the assignment of `is_trial` within the conditional in MSVC).

I'm not sure I understand the others; the comparison with zero is legal, and if anything I would think `std::fpclassify` would be better; and the implicit conversion from float to the double constructor seems to work as-is in GCC and MSVC, but maybe I'm missing an example test case where this breaks? And is the `sign` warning about a potential conflict with an existing standard identifier?

**Comment by sgrottel** [comment]
Sure. I will collect the concrete compiler settings and errors. From what I remember:
* Both `i` in `math::Unsigned` and `sign` in `math::Integer` where shadowing, either another local `i` or the class member `sign`
* One compile (I don't remember which. I have to check which) complained about the assignment within the `if`
* Same for the comparison to zero. I agree with your proposal, and will change my PR accordingly
* And, finally, the ctor from `float` was just for my convenience. There was one compiler warning about the implicit type change. I can remove that one, if you like, and manage this in my application code.

**Comment by possibly-wrong** [comment]
I did some testing and updated with the discussed changes (I think the `fpclassify` is safest for the zero comparison, and doesn't seem to observably affect speed), but I realize now that I created conflicts with your PR?

**Comment by sgrottel** [comment]
Hi! Thank you.
Yes, your changes make my pull request obsolete, I believe. I will close it for now. If I notice anything, I might create a new one in the future.

**Pull request closed without merging**
