### PR TITLE
Add to_precise_string (that detects repeating decimals)

### PR DESCRIPTION
**Pull request by LoganDark**
In order to avoid repeating decimals, I see that you've added rounding and truncation to the `to_string(size_t digits)` method. For fun, I wanted to try to implement a method that detects repeating decimals.

Enter: the `to_precise_string` function. I can't exactly give it the same name as the other to_string functions, since there's already an argument-less one and I didn't want to add some unrelated argument.

I attempted to replicate your.. interesting coding style. Some changes I made from my own code:
- Made variable names short and nonsensical
- Removed all blank lines
- Put braces on their own lines and removed any surrounding single statements
- Used no comments at all
- Indented with 4 spaces

Here's some test output from a program I made (1 divided by some prime numbers):

```
1/_?
> 3
0.(3)

1/_?
> 6
0.1(6)

1/_?
> 7
0.(142857)

1/_?
> 23
0.(0434782608695652173913)

1/_?
> 1223
0.(0008176614881439084219133278822567457072771872444807849550286181520850367947669664758789860997547015535568274734260016353229762878168438266557645134914145543744889615699100572363041700735895339329517579721995094031071136549468520032706459525756336876533115290269828291087489779231398201144726083401471790678659035159443990188062142273098937040065412919051512673753066230580539656582174979558462796402289452166802943581357318070318887980376124284546197874080130825838103025347506132461161079313164349959116925592804578904333605887162714636140637775960752248569092395748160261651676206050695012264922322158626328699918233851185609157808667211774325429272281275551921504497138184791496320523303352412101390024529844644317252657399836467702371218315617334423548650858544562551103843008994276369582992641046606704824202780049059689288634505314799672935404742436631234668847097301717089125102207686017988552739165985282093213409648405560098119378577269010629599345870809484873262469337694194603434178250204415372035977105478331970564186426819296811120196238757154538021259198691741618969746524938675388389206868356500408830744071954210956663941128372853638593622240392477514309076042518397383483237939493049877350776778413736713)
```

So yeah, it works. It's an "arbitrary-precision" `to_string` method, for your arbitrary-precision `Rational`. Enjoy :)

### CODE REVIEW

**Comment by LoganDark** [comment]
Also, this isn't the most efficient... I don't think maps and vectors are the best for this sort of thing. I think I can improve it if you don't merge this right away, though I'm not sure.

For example, 1/98374956 takes around 10 seconds or so.

**Comment by LoganDark** [comment]
Nevermind - this is definitely the correct way to check for repeating decimals... there's not much more I can do.

**Comment by LoganDark** [comment]
This makes repeating decimals look better in my calculator :)

image

**Comment by possibly-wrong** [comment]
Thanks-- although I don't plan to merge this addition, following are some comments explaining why:

First and most importantly, I actually intentionally left out this functionality, because it's potentially "dangerous," so to speak (this is the factorization issue I was referring to in previous discussion [here](https://github.com/possibly-wrong/precision/issues/2#issuecomment-429590575)). All of the implemented operators and other functions have predictable and well-behaved performance, in terms of both execution time and memory use. This function, however, does not-- consider your test 1/98374956, for example: try the only-slightly-different 1/98374957 instead to see what I mean.

Beyond that, for your reference, the current implementation yields a warning in MSVS 2015 about the potentially narrowing conversion in line 344 (e.g. on x64). The string lengths are `size_t`, recommend using that for the type in the map.

Finally, although I welcome constructive review, "interesting," "unreadable," and "nonsensical" are at best not sufficiently specific to be helpful or useful (I am guessing you are referring to the frequent single-letter variable names), and are at worst simply antagonistic and thus unlikely to encourage cooperation in future contributions.

**Comment by LoganDark** [comment]
About the narrowing conversion, on macOS strings use `unsigned long`, I guess I forgot that, IIRC, on all platforms `size_t` refers to that (not `unsigned long` specifically, but string lengths). I won't maintain this PR further, however.

Sorry for offending you.

**Pull request closed without merging**
